export const OFFER_STATUS = {
    WAIT_PUBLISH__WAIT_PRODUCT: 1,
    WAIT_PUBLISH__CHECK_PRODUCT: 2,
    PUBLISHING__ACTIVE: 3,
    PUBLISHING__PAUSE: 4,
    REJECT__CHECKING: 5,
    REJECT__RETURNING: 6,
    REJECT__DONE: 7,
    CANCEL__WAIT_TRADE: 8,
    CANCEL__NO_RETURN: 9,
    CANCEL__WAIT_RETURN: 10,
    CANCEL__RETURNING: 11,
    CANCEL__DONE: 12,
    STOP: 13,
};

export const OFFER_STATUS_TEXT = {
    [OFFER_STATUS.WAIT_PUBLISH__WAIT_PRODUCT]: '掲載待ち：商品送付待ち',
    [OFFER_STATUS.WAIT_PUBLISH__CHECK_PRODUCT]: '掲載待ち：商品確認待ち',
    [OFFER_STATUS.PUBLISHING__ACTIVE]: '掲載中：アクティブ',
    [OFFER_STATUS.PUBLISHING__PAUSE]: '掲載中：申請受付休止中',
    [OFFER_STATUS.REJECT__CHECKING]: '却下：却下中',
    [OFFER_STATUS.REJECT__RETURNING]: '却下：返送中',
    [OFFER_STATUS.REJECT__DONE]: '却下：却下済',
    [OFFER_STATUS.CANCEL__WAIT_TRADE]: 'キャンセル：取引完了待ち',
    [OFFER_STATUS.CANCEL__NO_RETURN]: 'キャンセル：返送不要',
    [OFFER_STATUS.CANCEL__WAIT_RETURN]: 'キャンセル：返送待ち',
    [OFFER_STATUS.CANCEL__RETURNING]: 'キャンセル：返送中',
    [OFFER_STATUS.CANCEL__DONE]: 'キャンセル：返送完了',
    [OFFER_STATUS.STOP]: '掲載差し止め',
}

export const OFFER_STATUS_OPTIONS = Object.values(OFFER_STATUS).map(value => ({
    value,
    label: OFFER_STATUS_TEXT[value],
}))

export const CANCELABLE_OFFER_STATUSES = [
    OFFER_STATUS.WAIT_PUBLISH__WAIT_PRODUCT,
    OFFER_STATUS.PUBLISHING__ACTIVE,
    OFFER_STATUS.PUBLISHING__PAUSE,
];

export const EDITABLE_OFFER_STATUSES = [
    OFFER_STATUS.WAIT_PUBLISH__WAIT_PRODUCT,
    OFFER_STATUS.WAIT_PUBLISH__CHECK_PRODUCT,
    OFFER_STATUS.PUBLISHING__ACTIVE,
    OFFER_STATUS.PUBLISHING__PAUSE,
];
