export const PRODUCT_ACCOUNT_ITEM_TYPE = {
    TEXT: 1,
    SELECT: 2,
    CHECKBOX: 3,
    RADIO: 4,
    IMAGE: 5,
};

export const PRODUCT_ACCOUNT_ITEM_TYPE_TEXT = {
    [PRODUCT_ACCOUNT_ITEM_TYPE.TEXT]: 'テキスト',
    [PRODUCT_ACCOUNT_ITEM_TYPE.SELECT]: 'セレクトボックス',
    [PRODUCT_ACCOUNT_ITEM_TYPE.CHECKBOX]: 'チェックボックス',
    [PRODUCT_ACCOUNT_ITEM_TYPE.RADIO]: 'ラジオボタン',
    [PRODUCT_ACCOUNT_ITEM_TYPE.IMAGE]: '画像',
}

export const PRODUCT_ACCOUNT_ITEM_TYPE_OPTIONS = Object.values(PRODUCT_ACCOUNT_ITEM_TYPE).map(value => ({
    value,
    label: PRODUCT_ACCOUNT_ITEM_TYPE_TEXT[value],
}))

export const MULTI_PRODUCT_ACCOUNT_ITEM_TYPE = [
    PRODUCT_ACCOUNT_ITEM_TYPE.SELECT,
    PRODUCT_ACCOUNT_ITEM_TYPE.CHECKBOX,
    PRODUCT_ACCOUNT_ITEM_TYPE.RADIO,
]
