# .tbls.yml
---
name: Phalcoデーターベース定義
dsn: my://root:password@host.docker.internal:3306/laravel?hide_auto_increment
dict:
  Tables: テーブル一覧
  Description: 概要
  Columns: カラム一覧
  Indexes: INDEX一覧
  Constraints: 制約一覧
  Triggers: トリガー
  Relations: ER図
  Name: 名前
  Comment: コメント
  Type: タイプ
  Default: デフォルト値
  Children: 子テーブル
  Parents: 親テーブル
  Definition: 定義
  Table Definition: テーブル定義
exclude:
  - migrations
  - job_batches
  - password_reset_tokens
  - administrator_password_reset_tokens
